CREATE table CONSULTATII (
	CNP 				BIGINT 		NOT NULL,
	NR_CONSULTATIE 		INT 		NOT NULL,
	DATA_CONSULTATIE 	DATE 		NOT NULL,
	DIAGNOSTIC 			VARCHAR(50) NOT NULL,
	MEDICAMENTATIE 		VARCHAR(100),
	PRIMARY KEY (CNP)
);

create table PACIENT (
	PID 			INT 		NOT NULL,
	CNP_FK 			BIGINT 		NOT NULL, 
	Adresa 			VARCHAR(50), 
	DataNasterii 	DATE 		NOT NULL,
	Varsta 			INT 		NOT NULL,
	PRIMARY KEY (PID),
	FOREIGN KEY (CNP_FK) REFERENCES CONSULTATII(CNP)
);